### ISSUE TITLE
Plans to Support hot-formula-parser?

### ISSUE THREAD

**Issue by on2air** [formulajs/formulajs#114]
Hi, looking forward to using library, but also need ability to parse/execute formulas as strings and prefer to not use eval() for security reasons.  Can I still use hot-formular-parser library? any plans to fork/support that?

**Comment by nicolashefti** [comment]
Hot formula parser is an archived repo from handsontable https://github.com/handsontable/formula-parser

It uses handsontable/formulajs another archived repo from handsontable https://github.com/handsontable/formula.js as dependency.

There is no plan to fork formula-parser to change the dependency to formulajs/formulajs instead of handsontable/formulajs.
