### ISSUE TITLE
Inconsistency in Date functions: mixing JSDate and sequential serial number (Excel date format)

### ISSUE THREAD

**Issue by maiers** [formulajs/formulajs#13]
These seems to be an inconsistency within the library, where some date functions return a JS date and others return a date serialized as a number. Which is also an inconsistency with Excel as Excel always returns dates as numbers, as Excel has no concept of a Date datatype.

It seems to be rather straightforward to create a pull request changing it in either direction, but I am unclear about what direction the library/community is planning to move. Direction welcome.

## Actual

    formatjs.DATE(2000,1,1)  // returns a JavaScript Date object [1]
    formatjs.DATEVALUE('1/1/2000') / / returns a number [2]

This also seems to apply to NOW and TODAY [3,4], possibly more of the date+time functions.

## Expected

Consistency.

I am not sure if these functions should return a JS date or a date serialized as a number. I believe there are good reasons for both to be found. But above all, they should be consistent in what they return. This is currently not the case.

If Excel compatibility is the highest goal, then all functions should return a "sequential serial number that represents a particular date" as per the Microsoft documentation [5,6,7,8].

[1] https://github.com/formulajs/formulajs/blob/6316d5f352787ab0f6191114eadf8675433e0a68/lib/date-time.js#L66-L84
[2] https://github.com/formulajs/formulajs/blob/6316d5f352787ab0f6191114eadf8675433e0a68/lib/date-time.js#L147-L166
[3] https://github.com/formulajs/formulajs/blob/6316d5f352787ab0f6191114eadf8675433e0a68/lib/date-time.js#L398-L400
[4] https://github.com/formulajs/formulajs/blob/6316d5f352787ab0f6191114eadf8675433e0a68/lib/date-time.js#L435-L441
[5] https://support.office.com/en-us/article/DATE-function-E36C0C8C-4104-49DA-AB83-82328B832349
[6] https://support.office.com/en-us/article/DATEVALUE-function-DF8B07D4-7761-4A93-BC33-B7471BBFF252
[7] https://support.office.com/en-us/article/NOW-function-3337FD29-145A-4347-B2E6-20C904739C46
[8] https://support.office.com/en-us/article/TODAY-function-5EB3078D-A82C-4736-8930-2F51A028FDD9

**Comment by nicolashefti** [comment]
Hi @maiers thanks for reporting this issue.

I agree with you there should be some consistency between all the functions having date outputs. 

## Actual situation

List of functions returning a date (JS or Excel-like).

JS Date:
- DATE
- TODAY
- NOW

Sequential Excel-like:
- DATEVALUE
- EDATE
- EOMONTH

## Direction?

A. What is speaking for JS Date:

1. The sequential number is a way for Excel to store a date. I don't think people tend to work directly with this sequential value but with the displayed formatted date value. They want to manipulate a date independently from the way it is stored. This is just internal to Excel.

2. Internally the library uses Js Date Object with the helper `utils.parseDate(serial_number);` which support sequential number, Js Date and also string. So the sequential returned actually by DATEVALUE is just a representation for the outer world. All computations appends on Date.

3. In terms of usability, if someone uses the JS library among in his/her code, he/she might want to deal with Date Object instead of the weird sequence that one has to convert to Date afterward.

B. What is speaking for Excel sequential:

1. Possibility to apply basic mathematical operator `formulajs.DATEVALUE("22-MAY-2011")+3` will output `40688 (Number formatted)`. With the JS Date Object this won't work.

The A option looks more natural too me as a JavaScript developer using the library.

What do you think? Do you see other points in A or B?

**Comment by maiers** [comment]
In the end, it boils down to how the API is used. If people are looking for something where they can basically copy+paste their Excel formulas into JS then the answer is different then if we are looking to call maybe one or two Excel functions from JS.

Diving a bit further into this topic, we also have to consider the input side, as e.g. DAY [1] currently expects a serial number as parameter. To allow composition within the functions themselves, all of them need to follow the same pattern. So either it's always JS Date or always the serial number.

Following the tag line "Community built JavaScript implementation of most Microsoft Excel formula functions." I personally would vote for adhering to the API as defined by Excel.

To allow interoperability with JS, one could add public converter functions between JS Date <=> serial number. That way interoperability with JS is provided but the API is compatible to its big brother. 

[1] https://github.com/formulajs/formulajs/blob/master/lib/date-time.js#L168-L175

**Comment by nicolashefti** [comment]
For interoperability reason I believe adding 2 functions (SEQ_TO_DATE and DATE_TO_SEQ) makes total sense.

Function inputs are not really an issue. As mentioned in A.2 all date-like inputs are parsed in the library using the `utils.parseDate()`. This utility is able to deal with string, JS Date and serial number. It returns a Js Date and all computation are done using Js Date in the library itself.

The question is now what is the standard date output of the library?

Based on Microsoft documentation, DATE is among the [10 most used functions](https://support.office.com/en-us/article/Excel-functions-by-category-5f91f4e9-7b42-46d2-9bd1-63f26a86c0eb). This functions is currently returning a JS Date in formulajs. If we assume some kind of similarity between Excel and formulajs usage, then using Js Date for DATEVALUE, EDATE, EOMONTH will be a minor breaking change. Changing the return type of one of most used function can break a lot of projects.

This project is a fork of https://github.com/handsontable/formula.js. In this project they have also the same kind of function usage than in Excel. They were using the Js Date output of the function DATE. This would speak again for Js Date being the standard output.

**Comment by nicolashefti** [comment]
@maiers any opinion of my last comment and what should be the standard date output type?

**Comment by maiers** [comment]
It all boils down to the usage pattern of library. If it's (mostly) single function calls I believe returning a JS Date is the sensible solution. As this is also the current implementation and there seems to be no general support for a change, this is likely the way to go.

But it needs to be clear that under this assumption, copying (an English language) composite formula directly from Excel into JS will not work out of the box:

    = DATE(2020,5,9) - DATE(2020,5,8) // formulajs: 86400000 / excel: 1

**Comment by goldsmithjim** [comment]
Also take a look at https://github.com/davidpolberger/formulajs/commit/4a467027d433bcb1cf5ff66b7de837285028034c
