### ISSUE TITLE
QUESTION: Should ISBLANK return false for empty string

### ISSUE THREAD

**Issue by nikazooz** [formulajs/formulajs#30]
This is more of a question.

Should ISBLANK return false if empty string is given?

If not I can submit a PR to change this

**Comment by nicolashefti** [comment]
You mean ISBLANK ? There a bit of discussion around this one :

A1 =CONCAT("") => Empty string
A2 = ISBLANK(A1) => False

_It's probably best to think of ISBLANK to mean "is empty" since it can return FALSE when cells look blank but aren't. For example, if A1 contains a space character (" "), or a formula that returns an empty string (""), A1 will look blank , but ISBLANK(A1) will return FALSE in both cases._ [Quote](https://exceljet.net/excel-functions/excel-isblank-function)

In our case we are always working with values and not cell reference, which would be ideal to recreate ISBLANK correctly.

Maybe extend the current code to null and undefined.

What do you think ?

**Comment by nikazooz** [comment]
Yes, I meant ISBLANK... Thanks for the explanation, makes sense. Don't know if anything should change
