### ISSUE TITLE
Issue with HYPGEOM.DIST

### ISSUE THREAD

**Issue by GreeshmakRaj** [formulajs/formulajs#45]
Excel returns value 0.990847 for =HYPGEOM.DIST(11,14,18,30,1). The same formula returns error(#ERROR) when using formulajs.

**Comment by nicolashefti** [comment]
@GreeshmakRaj thanks for reporting the issue. Can you investigate of what might cause the error ?

**Comment by GreeshmakRaj** [comment]
`function pdf(x, n, M, N) {
    return mathTrig.COMBIN(M, x) * mathTrig.COMBIN(N - M, n - x) / mathTrig.COMBIN(N, n);
  }`
This function is being called inside HYPGEOM.DIST definition. 
For cumulative = true, cdf(x, n, M, N) function is called and inside it pdf(x, n, M, N) function is called. 
For cumulative = false, pdf(x, n, M, N) is directly called.
When we use HYPGEOM.DIST(11,14,18,30,1) => cdf(11,14,18,30) => pdf(0,14,18,30) is called which returns "RangeError: Maximum call stack size exceeded" error.

**Comment by nicolashefti** [comment]
"Max call stack" is due to the recursive function FACT used in COMBIN. If you call FACT with a negative number you will get the same error.

My hypothesis: with your parameters, FACT gets called somehow with a negative number and crashes. We could add a unit test to return error.num to avoid this crash. But it would not help to calculate your initial formula.

Can you check if the algorithm to calculate "HYPGEOM.DIST" is correct? Or if there is an alternative to the one used?

**Comment by GreeshmakRaj** [comment]
@nicolashefti After adding a check for positive number in FACT, the issue is resolved. Thank you!

**Comment by nicolashefti** [comment]
Do you want to make a pull-request to patch the FACT function?

**Comment by GreeshmakRaj** [comment]
Yeah sure.
