### ISSUE TITLE
Tests fail in certain timezones

### ISSUE THREAD

**Issue by manuphatak** [formulajs/formulajs#85]
## Problem

When I first pulled the repo and ran the tests, I got 3 date-related test failures.

**Failing Tests**
- https://github.com/formulajs/formulajs/blob/a4ddfd41af18534d5898bb1b8dbc1e0df43cece1/test/date-time.js#L52
- https://github.com/formulajs/formulajs/blob/a4ddfd41af18534d5898bb1b8dbc1e0df43cece1/test/date-time.js#L71
- https://github.com/formulajs/formulajs/blob/a4ddfd41af18534d5898bb1b8dbc1e0df43cece1/test/utils/common.js#L158

![image](https://user-images.githubusercontent.com/5052422/148270911-4d6878de-18fa-4cbc-a57b-c12d66e7ba08.png)

I can solve these by setting the timezone to `Europe/Warsaw`:

```sh
export TZ=Europe/Warsaw
```

Even though setting the timezone fixes the test failures, the tool and tests should not be dependent on any particular timezone.

**Context**

My time zone is `America/Los_Angeles`. The steps to recreate:

```sh
export TZ=America/Los_Angeles
make test
```

Other timezones I tried:

<table>
<tr>
	<td>timezone
	<td>pass/fail
<tr>
	<td>America/Los_Angeles
	<td>fail
<tr>
	<td>America/Chicago
	<td>fail
<tr>
	<td>America/New_York
	<td>fail
<tr>
	<td>Asia/Calcutta
	<td>pass
<tr>
	<td>Europe/Warsaw
	<td>pass
</table>

related links: 
- Conversation started here #83

**Comment by nicolashefti** [comment]
Thanks for the detailed problem report @manuphatak 

On my side the step to recreate is: `env TZ='America/Chicago' node_modules/.bin/mocha`

The function serialNumberToDate is new (see #76). I think it has something to do with the new Date using a timestamp:

https://github.com/formulajs/formulajs/blob/a4ddfd41af18534d5898bb1b8dbc1e0df43cece1/lib/utils/common.js#L182

According to https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/date/date

"Time value or timestamp number

An integer value representing the number of milliseconds since January 1, 1970, 00:00:00 UTC (the ECMAScript epoch, equivalent to the UNIX epoch), with leap seconds ignored. Keep in mind that most UNIX Timestamp functions are only accurate to the nearest second."

**Comment by nicolashefti** [comment]
@manuphatak I made some test using a different time zone than mine.

I think I fixed serialNumberToDate adujsting the new Date from timestamp to the locale TZ.

Now, I still have a few tests failing for DATEDIF, which I think are related to the tests themself. The library is using ISO String format:

`dateTime.DATEDIF('2007-01-01', '2008-07-01', 'm').should.equal(18);`

But this format is treated [as UTC](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date): "Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local."

Using this notation works accross TZ:

`dateTime.DATEDIF(new Date(2007, 1, 1), new Date(2008, 7, 1), 'm').should.equal(18);`

Formula.js is not a date parsing library. Maybe we should just change the way functions are tested. What do you think?

**Comment by manuphatak** [comment]
@nicolashefti I think it's safe to close this issue.  Following up on the convo in #83, it looks like the time zone issues are totally resolved!
